added auth and fixes

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -1,99 +1,117 @@
 #!/bin/sh
-# The URL to send the commit information to
-match="false"
-url=$(git config hooks.tagretcommiturl || echo $match)
+error="false"
+
+# The URL to login 
+# "http://erpal.local/rest/git/user/login"
+loginurl=$(git config hooks.tagretloginurl || echo $error) 
 # check URL
-if [ $url != $match ]; then
-	while read oldrev newrev ref
-	do
-		# prepare our JSON object
-		json="
-		{
-			\"before\": \"$oldrev\",
-			\"after\": \"$newrev\",
-			\"commits\": [
-			"
-			comma=""
-			for rev in $(git rev-list $oldrev..$newrev)
-			do
-				# first comma check
-				json+="$comma"
-				if [ $comma=="" ]; then
-					comma=","
-				fi
-				
-				# prepare JSON for commit
-				json+="{"
-					# id
-					json+="\"id\": \"$rev\","
-					# message
-					message=$(git cat-file commit $rev | sed '1,/^$/d')
-					json+="\"message\": \"$message\","
-					
-					# Author
-					author_line=$(git cat-file commit $rev | sed '1,2d' | sed '2~2d')
-					json+="\"author\": {";
-						# email
-						email=$(echo $author_line | sed -r 's/.*<//' | sed -r 's/>.*//')
-						json+="\"email\": \"$email\","
-						# name
-						author=$(echo $author_line | sed -r 's/author //')
-						name=$(echo $author | sed -r 's/\s<.*//')
-						json+="\"name\": \"$name\""
-					json+="},";
-					
-					# Committer
-					committer_line=$(git cat-file commit $rev | sed '1,3d' | sed '3~3d')
-					json+="\"committer\": {";
-						# email
-						committer_email=$(echo $committer_line | sed -r 's/.*<//' | sed -r 's/>.*//')
-						json+="\"email\": \"$committer_email\","
-						# name
-						committer=$(echo $committer_line | sed -r 's/committer //')
-						name=$(echo $committer | sed -r 's/\s<.*//')
-						json+="\"name\": \"$name\""
-					json+="},";
-					
-					# timestamp
-					time=$(echo $author_line | sed -r 's/.*>\s//')
-					# timestamp format: "2008-02-15T14:36:34-08:00"
-					timastamp=$(perl -mbigint -mPOSIX -e "print( POSIX::strftime(\"%Y-%m-%dT%H:%M:%S\",localtime( $time ) ))")
-					# @todo: what is "-08:00" in this format?
-					json+="\"timestamp\": \"$timastamp\","
-					
-					# added
-					json+="\"added\": []"
-					# @todo: url, distinct, modified, removed
-				json+="}"
-			done
+if [ $loginurl == $error ]; then
+	# URL error
+	echo "error: Login failed"
+	echo "You must configure your repository and set \"tagretloginurl\" config paraneter"
+	echo "Go to your repository and run: git config hooks.tagretloginurl <url>"
+	echo "Or add \"tagretloginurl\" parameter to your config file"
+	exit
+fi
 
-			json+="
-				],
-				\"ref\": \"$refname\","
-			
-			# repository
-			json+="\"repository\": {"
-				# @todo: url
-				#repository_url=$(git config remote.origin.url)
-				json+="\"url\": \"\","
-				# @todo: name
-				json+="\"name\": \"\""
-			json+="}"
-		json+="}"
+curl -b /tmp/cookie_git -c /tmp/cookie_git -s "username=git&password=git" "$loginurl"
 
-		# send JSON
-		curl POST -d "payload=$json" "$url"
-		
-		## for debugging ##
-		#echo $json
-		#curl -v -H -X POST -d "payload=$json" "$url"
-		#echo $(git config -l)
-	done
-else
+# The URL to send the commit information to 
+# "http://erpal.local/rest/git/git/commit"
+url=$(git config hooks.tagretcommiturl || echo $error) 
+# check URL
+if [ $url == $error ]; then
 	# URL error
 	echo "error: Commits information wasn't sent"
 	echo "You must configure your repository and set \"tagretcommiturl\" config paraneter"
 	echo "Go to your repository and run: git config hooks.tagretcommiturl <url>"
-	echo "Or add \"tagretcommiturl\" parameter to your .git/config file"
+	echo "Or add \"tagretcommiturl\" parameter to your config file"
+	exit
 fi
 
+while read oldrev newrev ref
+do
+	# prepare our JSON object
+	json="
+	{
+		\"before\": \"$oldrev\",
+		\"after\": \"$newrev\",
+		\"commits\": [
+		"
+		comma=""
+		for rev in $(git rev-list $oldrev..$newrev)
+		do
+			# first comma check
+			json+="$comma"
+			if [ $comma=="" ]; then
+				comma=","
+			fi
+			
+			# prepare JSON for commit
+			json+="{"
+				# id
+				json+="\"id\": \"$rev\","
+				# message
+				message=$(git cat-file commit $rev | sed '1,/^$/d')
+				json+="\"message\": \"$message\","
+				
+				# Author
+				author_line=$(git cat-file commit $rev | sed '1,2d' | sed '2~2d')
+				json+="\"author\": {";
+					# email
+					email=$(echo $author_line | sed -r 's/.*<//' | sed -r 's/>.*//')
+					json+="\"email\": \"$email\","
+					# name
+					author=$(echo $author_line | sed -r 's/author //')
+					name=$(echo $author | sed -r 's/\s<.*//')
+					json+="\"name\": \"$name\""
+				json+="},";
+				
+				# Committer
+				committer_line=$(git cat-file commit $rev | sed '1,3d' | sed '3~3d')
+				json+="\"committer\": {";
+					# email
+					committer_email=$(echo $committer_line | sed -r 's/.*<//' | sed -r 's/>.*//')
+					json+="\"email\": \"$committer_email\","
+					# name
+					committer=$(echo $committer_line | sed -r 's/committer //')
+					name=$(echo $committer | sed -r 's/\s<.*//')
+					json+="\"name\": \"$name\""
+				json+="},";
+				
+				# timestamp
+				time=$(echo $author_line | sed -r 's/.*>\s//')
+				# timestamp format: "2008-02-15T14:36:34-08:00"
+				# @todo: what is "-08:00" in this format?
+				# %Y-%m-%dT%H:%M:%S
+				timastamp=$(perl -mbigint -mPOSIX -e "print( POSIX::strftime(\"%Y-%m-%d %H:%M:%S\",localtime( $time ) ))") 
+				json+="\"timestamp\": \"$timastamp\","
+				
+				# added
+				json+="\"added\": []"
+				# @todo: url, distinct, modified, removed
+			json+="}"
+		done
+
+		json+="
+			],
+			\"ref\": \"$refname\","
+		
+		# repository
+		json+="\"repository\": {"
+			# @todo: url
+			#repository_url=$(git config remote.origin.url)
+			json+="\"url\": \"\","
+			# @todo: name
+			json+="\"name\": \"\""
+		json+="}"
+	json+="}"
+
+	# send JSON
+	#curl -b /tmp/cookie_git -c /tmp/cookie_git -s "payload=$json" "$url"
+	
+	## for debugging ##
+	echo $json
+	curl -b /tmp/cookie_git -c /tmp/cookie_git -v -H -X POST -d "payload=$json" "$url"
+	#echo $(git config -l)
+done
